package se.bassac.roster.dao;

/**
 * Business Methods interface for entity DAthlete.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-06-11T20:55:17.286+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DAthleteDao extends GeneratedDAthleteDao {

	// TODO: declare your Business Methods here
	
}
