package se.bassac.roster.dao;

/**
 * Implementation of Business Methods related to entity DAthlete.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-06-11T20:55:17.286+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DAthleteDaoBean 
	extends GeneratedDAthleteDaoImpl
		implements DAthleteDao 
{

	// TODO: implement your Business Methods here

}
