package se.bassac.roster.dao;

/**
 * Implementation of Business Methods related to entity DOrganizer.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-06-14T20:04:52.499+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DOrganizerDaoBean 
	extends GeneratedDOrganizerDaoImpl
		implements DOrganizerDao 
{

	// TODO: implement your Business Methods here

}
