package se.bassac.roster.dao;

/**
 * Business Methods interface for entity DOrganizer.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-06-14T20:04:52.499+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DOrganizerDao extends GeneratedDOrganizerDao {

	// TODO: declare your Business Methods here
	
}
