package se.bassac.roster.dao;

/**
 * Implementation of Business Methods related to entity DTrack.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-06-12T21:06:02.657+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DTrackDaoBean 
	extends GeneratedDTrackDaoImpl
		implements DTrackDao 
{

	// TODO: implement your Business Methods here

}
