package se.bassac.roster.dao;

/**
 * Business Methods interface for entity DTrack.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-06-12T21:06:02.657+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DTrackDao extends GeneratedDTrackDao {

	// TODO: declare your Business Methods here
	
}
